In [1]:
# Assume a 4-port parameter being remapped to 6-ports.
# I'm adding crosstalk from one line to another one.

import numpy as np

In [2]:
S4 = np.array([[11,12,13,14],
               [21,22,23,24],
               [31,32,33,34],
               [41,42,43,44]])

B12 = np.array([[1,0], [0,1], [0,0], [0,0]])
B34 = np.array([[0,0], [0,0], [1,0], [0,1]])

Sx = np.matmul(np.matmul(B12.T, S4), B34)
print(Sx)

[[13 14]
 [23 24]]


In [3]:
A12 = np.array([[1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0]])
A56 = np.array([[0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 1]])

S6 = np.matmul(np.matmul(A56.T, Sx), A56)
print(S6)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 13 14]
 [ 0  0  0  0 23 24]]
